server:
  port: 7777

spring:
  application:
    name: Revision
  datasource:
    username: system
    password: Abhay@123
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      show-sql: true
    ddl-auto: update