server:
  port: 9090

spring:
  application:
    name: Spring_CRUD
  datasource:
    username: system
    password: 31082002
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: update