server:
  port: 9999
spring:
  application:
    name: Crud_Revision
  datasource:
    username: system
    password: 31082002
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: update